### ISSUE TITLE
the presurfer script's references

### ISSUE THREAD

**Issue by JayJoemary** [srikash/presurfer#1]
I have two questions.
1.I wonder whether it based on the medthod of the article "Robust T1-Weighted Structural Brain Imaging and Morphometry at 7T Using MP2RAGE"
2.the presurf_MP2RAGEise.m：uni_img_clean = uni_img.*inv2_img_norm;
what does ". * " mean?
Would you mind interpreting this for me?
Thank you.

**Comment by srikash** [comment]
Hi @JayJoemary so sorry for my delayed reply! Not sure if it's still an open question for you but : (1) while the outcome of the script achieves removal of the noisy background, it's not the same as the article. Code for that approach is available from the creators [here](https://github.com/JosePMarques/MP2RAGE-related-scripts/blob/master/DemoRemoveBackgroundNoise.m). (2) that is an element-wise multiplication operator in MATLAB.
