### ISSUE TITLE
repository of mp2rage

### ISSUE THREAD

**Issue by andraderenew** [srikash/presurfer#3]
Hello! 

I would be interested in practicing with this toolbox. But unfortunately I don't have MP2RAGE images. Is there somewhere over internet I can get at least one image to practice? 

Thanks for the help in advance!

**Comment by srikash** [comment]
Hey Rene, there is also the [AHEAD dataset](https://uvaauas.figshare.com/articles/dataset/AHEAD_structural_MRI_Data/8332325). This dataset has 4 INV2 echoes however. For presurfer, you can use the first echo of INV2.
