### ISSUE TITLE
issue with freesurfer segmentation

### ISSUE THREAD

**Issue by andraderenew** [srikash/presurfer#4]
Hi! I am having an issue with freesurfer recon-all processing. I do all presurfer steps without any error. And then I do 

recon-all -all -i MPRAGEised_stripped.nii.gz -s fsm08un_MPRAGEised -openmp 8

I have used this subject database. Then I use subject “fsm08un”. 

https://secure-web.cisco.com/1DoAeFvUHnYto_t5xoLbWcFtbuOwQtmlS1ENoWBmeeHffDpNErW4_gUBNrL5wbRsqdn8Lvt8o-hftAn4O3mHZlavh98oBX5sjSMs6gyoyT47B4jGytWCy0opSP505tXZd0usKIHMHIWlSmIqHKG6eDzK-1hhavHJFtmcsFeyidS8mPmaHdP-KpuCotmuwqgIPCppobf5sCRfNWndHYDvrfUWS7cnm05Gepyhhd9wWDL3SOx7eMSw78OvBAoGp4jAtzA51dgT22RZWjsiDkVkZhxVB65cvL3d0EEIQEb3b-Pvc_aXfazlGDtAv_BN8ebkALkCERCl8XVgThOSIi-yo1DOledDb39I-AMQQIyh_XeQ/https%3A%2F%2Fsurfer.nmr.mgh.harvard.edu%2Ffswiki%2FFsmData

Rene.

**Comment by srikash** [comment]
Hi Rene,

Thanks for using presurfer. Could you specify what error you're getting when you run FS?

Thanks,
Sri

**Comment by andraderenew** [comment]
Weighting the input with prior template 

****************TEMPLATE DEFORMATION****************

      second estimation of the COG coord: x=130,y=125, z=130, r=124102 iterations
^^^^^^^^ couldn't find WM with original limits - expanding ^^^^^^

   GLOBAL      CSF_MIN=1, CSF_intensity=2, CSF_MAX=4 , nb = -1447023003
  RIGHT_CER    CSF_MIN=1, CSF_intensity=2, CSF_MAX=4 , nb = -1862269955
  LEFT_CER     CSF_MIN=1, CSF_intensity=2, CSF_MAX=4 , nb = -230683617
 RIGHT_BRAIN   CSF_MIN=1, CSF_intensity=2, CSF_MAX=4 , nb = 1409286624
 LEFT_BRAIN    CSF_MIN=1, CSF_intensity=2, CSF_MAX=4 , nb = 943723776
    OTHER      CSF_MIN=1, CSF_intensity=2, CSF_MAX=4 , nb = 943755195
mri_watershed Error: 
 GLOBAL region of the brain empty !
Darwin Renes-MacBook-Air.local 22.5.0 Darwin Kernel Version 22.5.0: Thu Jun  8 22:22:19 PDT 2023; root:xnu-8796.121.3~7/RELEASE_ARM64_T8103 arm64

recon-all -s fsm08un_MPRAGEised exited with ERRORS at Tue Aug  1 15:40:57 CEST 2023


**If you need the whole recon-all.log let me know.**

**Comment by srikash** [comment]
Ah yes. All too familiar. Try running : `recon-all -autorecon1 -i MPRAGEised.nii.gz -s fsm08un_MPRAGEised -openmp 8 -xmask stripmask.nii.gz` and for subjects like this, you could also include the `-bigventricles` flag. 

Another thing that is useful to know is you can turn off the watershed option by giving `-watershed nowatershed`.

Let me know if that worked out, I'll update the documentation. Perhaps it's just good practice to use the `-xmask` flag always!

**Comment by andraderenew** [comment]
Two doubts when do I know I have to use flag -bigventricules? Is it because these patients have dementia or anything ? -no watershed flag is used or not mandatory? What happens if I use or not. Which one to use ? 

Can I run from the start recon-all -all -i MPRAGEised.nii.gz -s fsm08un_MPRAGEised -openmp 8 -xmask stripmask.nii.gz???

**Comment by andraderenew** [comment]
sorry to insist but I dont know who else to ask for this.

**Comment by srikash** [comment]
> Can I run from the start recon-all -all -i MPRAGEised.nii.gz -s fsm08un_MPRAGEised -openmp 8 -xmask stripmask.nii.gz???

yes indeed. I tested it on your fsm08_un dataset. It progresses as expected without throwing that error.

**Comment by srikash** [comment]
> Two doubts when do I know I have to use flag -bigventricules? Is it because these patients have dementia or anything ? -no watershed flag is used or not mandatory? What happens if I use or not. Which one to use ?

With the stripmask, you won't have to bother with the watershed flag at all.  

These were just "good-to-know" flags. FS in my experience works well without needing to tweak or customise much, even for patients/aged cohorts. If you find something work sub-optimally, you can try those flags. But also good to note that there is a [Freesurfer Mailing List](https://www.mail-archive.com/freesurfer@nmr.mgh.harvard.edu/) wherein the devs / community answer the tool-specific questions and help out.

I will close this issue as I think the MPRAGEised with stripmask will now work. Please feel free to re-open if you still encounter issues.

----------- ps
Going to leave this reference to a comment about MP2RAGE datasets in issue https://github.com/srikash/presurfer/issues/3#issuecomment-1671319642
